CFLAGS += -Werror
CFLAGS += -Wno-sign-compare
CFLAGS += -Wno-type-limits
CFLAGS += -Wno-unused-variable
CFLAGS += -Wno-unused-function
CFLAGS += -Wno-unused-label
CFLAGS += -Wno-unused-parameter
CFLAGS += -Wno-unused-but-set-variable
